name: Build Android APK (Unity)

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('**/*.cs', 'Packages/manifest.json', 'Packages/packages-lock.json', 'ProjectSettings/ProjectSettings.asset') }}
          restore-keys: |
            Library-Android-

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2021.1.6f1
          targetPlatform: Android
          androidAppBundle: false
          buildName: NewBark
          buildPath: build
          allowDirtyBuild: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/*.apk
          if-no-files-found: warn
