name: Generate Unity Activation File (.alf)

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activation file inside Unity Docker
        shell: bash
        run: |
          set -euo pipefail
          WORKDIR="$PWD"
          IMAGE="unityci/editor:2021.1.6f1-base-3"
          echo "Pulling $IMAGE"
          docker pull "$IMAGE"
          echo "Running Unity to create activation file..."
          docker run --rm -v "$WORKDIR":/project -w /project "$IMAGE" bash -lc '
            set -e
            /opt/unity/Editor/Unity -batchmode -nographics -quit -logFile /project/alf-generation.log -createManualActivationFile || true
            echo "Searching for .alf files..."
            find /root /root/.local/share/unity3d -maxdepth 6 -type f -name "*.alf" -print || true
            for f in $(find /root /root/.local/share/unity3d -maxdepth 6 -type f -name "*.alf" 2>/dev/null); do
              echo Copying "$f" to /project/
              cp -v "$f" /project/
            done
          '
          echo "Workspace contents after run:"
          ls -al

      - name: Prepare base64 of activation file
        shell: bash
        run: |
          set -e
          if ls *.alf >/dev/null 2>&1; then
            FILE=$(ls *.alf | head -n1)
            base64 -w0 "$FILE" > alf-base64.txt
          else
            echo "No .alf found" > no-alf.txt
          fi

      - name: Upload activation file artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: "*.alf"
          if-no-files-found: warn

      - name: Upload base64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file-base64
          path: alf-base64.txt
          if-no-files-found: warn

      - name: Upload generation log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alf-generation-log
          path: "alf-generation.log"
          if-no-files-found: warn

      - name: Add summary
        if: always()
        shell: bash
        run: |
          {
            echo "### Unity activation (.alf) status"
            if ls *.alf >/dev/null 2>&1; then
              echo ""
              echo "Activation request (.alf) generated successfully."
              echo ""
              echo "- Download the 'unity-activation-file' artifact (.alf) or copy the base64 below."
              echo "- Visit https://license.unity3d.com/manual to upload the .alf and download your .ulf."
              echo "- Base64 the .ulf and save as repo secret UNITY_LICENSE."
              echo ""
              if [ -f alf-base64.txt ]; then
                echo "<details><summary>Click to show .alf base64</summary>"
                echo ""
                cat alf-base64.txt
                echo ""
                echo "</details>"
              fi
            else
              echo ""
              echo "No .alf found. Unity may have failed to create the activation file."
              echo ""
              echo "- Download the 'alf-generation-log' artifact to inspect errors."
              echo "- This workflow does NOT require UNITY_LICENSE; it generates the request."
            fi
          } >> "$GITHUB_STEP_SUMMARY"
