name: Generate Unity Activation File (.alf)

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create activation file via Unity docker
        shell: bash
        run: |
          set -euo pipefail
          IMAGES=(
            ghcr.io/game-ci/unity-editor:2021.1.6f1-base-3
            ghcr.io/game-ci/unity-editor:2021.1.6f1-base
            unityci/editor:2021.1.6f1-base-3
            unityci/editor:2021.1.6f1-base
          )
          CREATED=0
          for IMG in "${IMAGES[@]}"; do
            echo "Trying image: $IMG"
            if docker pull "$IMG"; then
              if docker run --rm -v "$PWD":/project -w /project "$IMG" bash -lc \
                "/opt/unity/Editor/Unity -batchmode -nographics -quit -logFile /root/alf-generation.log -createManualActivationFile || true"; then
                CREATED=1
                break
              fi
            fi
          done
          if [[ "$CREATED" -eq 0 ]]; then
            echo "Failed to run Unity to create activation file"
          fi
          echo "Searching for .alf files and copying to workspace..."
          set +e
          docker run --rm -v "$PWD":/project "$IMG" bash -lc "\
            set -e; \
            for d in /root /root/.local/share/unity3d /root/.local/share/unity3d/Unity /home /home/unity /; do \
              echo Checking $d; \
            done; \
            echo 'Find results:'; \
            find /root /root/.local/share/unity3d /project -maxdepth 6 -type f -name '*.alf' -print || true; \
            for f in $(find /root /root/.local/share/unity3d /project -maxdepth 6 -type f -name '*.alf' 2>/dev/null); do \
              echo Copying $f; \
              cp -v "$f" /project/; \
            done; \
            cp -v /root/alf-generation.log /project/ 2>/dev/null || true; \
          " || true
          echo "Workspace contents:"
          ls -al || true

      - name: Upload activation file artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: "*.alf"
          if-no-files-found: warn

      - name: Upload generation log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alf-generation-log
          path: "alf-generation.log"
          if-no-files-found: warn
