name: Unity Activation (Request .alf)

on:
  workflow_dispatch:

jobs:
  request-activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request Unity Activation File
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2021.1.6f1

      - name: Upload activation file artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: "*.alf"
